# base_model: mistralai/Mistral-7B-v0.1
# model_type: MistralForCausalLM
# tokenizer_type: LlamaTokenizer

# load_in_8bit: false
# load_in_4bit: false
# strict: false

# # to fix multiprocessing error
# # dataset_processes: 64

# datasets:
#   - path: /home/rslm/ABC_scripts/processed_dataset/data_1.jsonl
#     type: alpaca
# # dataset_prepared_path: /workspace/axolotl/last_run_prepared
# val_set_size: 0.05
# output_dir: /home/rslm/ABC_scripts/axolotl_output_dir

# # sequence_len: 131072 # 4096*32, previously 4096*2
# sequence_len: 16384 # 4096*4
# # sequence_len: 8192
# pad_to_sequence_len: false
# eval_sample_packing: false

# gradient_accumulation_steps: 1
# micro_batch_size: 1
# eval_batch_size: 1
# # num_epochs: 4
# num_epochs: 8
# optimizer: adamw_bnb_8bit
# lr_scheduler: cosine
# learning_rate: 0.000005

# train_on_inputs: false
# group_by_length: false

# gradient_checkpointing: true
# logging_steps: 1

# warmup_steps: 1
# evals_per_epoch: 1
# saves_per_epoch: 1




eval_sample_packing: False

base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /home/rslm/ABC_scripts/processed_dataset/data_1.jsonl
    type: alpaca
# dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: /home/rslm/ABC_scripts/axolotl_output_dir

adapter: qlora
lora_model_dir:

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true
# flash_attention: false

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens: