base_model: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /workspace/copy_to_pod/small_data.jsonl
    type: alpaca
dataset_prepared_path:
val_set_size: 0.05
output_dir: ./runpodvol/out

# sequence_len: 131072 # 4096*32, previously 4096*2
# sequence_len: 16384 # 4096*4
sequence_len: 10000
sample_packing: true
pad_to_sequence_len: false
eval_sample_packing: false

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
eval_batch_size: 1
# num_epochs: 4
num_epochs: 8
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.000005

train_on_inputs: false
group_by_length: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 2
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
weight_decay: 0.0
fsdp:
fsdp_config: